#node js language
language: node_js
node_js:
    - "11.11.0"

before_script:
    - npm update

#safelist
braches:
    only:
    - master
    - supertest
    - cascade-artisan

services: mongodb

script:
    - npm test
    - npm coverage
